import { useCallback, useEffect, useMemo, useState } from 'react'
import { api, tokenStore } from './api'
import ReactMarkdown from 'react-markdown'

const NAV=[['dashboard','⌂','Dashboard'],['planner','▦','Planner'],['subjects','◎','Subjects'],['coach','✦','AI Coach'],['resources','⌕','Resources'],['settings','⚙','Settings']]
const COLORS=['#6D5DFB','#00A88B','#FF8C55','#E75580','#3488FF','#9A5DE2']
const todayPlus=(n)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}
const niceDate=(v)=>v?new Date(`${v}T12:00:00`).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'}):''
const timeLabel=(m)=>{const h=Math.floor(m/60)%24,mm=m%60;return `${h%12||12}:${String(mm).padStart(2,'0')} ${h>=12?'PM':'AM'}`}

function Auth({onAuth}){
  const [mode,setMode]=useState('register'),[form,setForm]=useState({name:'',email:'',password:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const body=mode==='login'?{email:form.email,password:form.password}:form;const data=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});tokenStore.set(data.access_token);onAuth(data.user)}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <div className="auth-shell"><div className="orb o1"/><div className="orb o2"/><div className="auth-card"><Brand dark/><div className="eyebrow">STUDY SMARTER · PREPARE CALMER</div><h1>{mode==='register'?'Build your exam plan.':'Welcome back.'}</h1><p className="muted">A teacher-style planner that turns subjects, weak topics and exam dates into an achievable daily schedule.</p><form className="form" onSubmit={submit}>{mode==='register'&&<label>Name<input required minLength="2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Working…':mode==='register'?'Create account':'Sign in'}</button></form><button className="link-btn" onClick={()=>{setMode(mode==='register'?'login':'register');setError('')}}>{mode==='register'?'Already have an account? Sign in':'New here? Create an account'}</button></div></div>
}
function Brand({dark=false}){return <div className={`brand ${dark?'dark':''}`}><span className="logo">S</span><b>StudyPilot <i>AI</i></b></div>}
function Sidebar({page,setPage,user,logout}){return <aside><Brand/><nav>{NAV.map(([id,icon,label])=><button key={id} onClick={()=>setPage(id)} className={page===id?'active':''}><span>{icon}</span>{label}</button>)}</nav><div className="tip"><b>Teacher tip</b><p>Finish today’s planned work before adding extra chapters.</p></div><div className="profile"><span>{user.name?.[0]?.toUpperCase()}</span><div><b>{user.name}</b><small>{user.email}</small></div><button onClick={logout}>↪</button></div></aside>}
function Header({title,sub}){return <header><div><div className="eyebrow">PERSONAL STUDY WORKSPACE</div><h2>{title}</h2><p>{sub}</p></div><div className="today"><span>Today</span><b>{new Date().toLocaleDateString(undefined,{month:'short',day:'numeric'})}</b></div></header>}
function Empty({title,text,action,onClick}){return <div className="empty"><span>✦</span><b>{title}</b><p>{text}</p>{action&&<button className="secondary" onClick={onClick}>{action}</button>}</div>}
function Ring({value}){return <div className="ring" style={{'--v':`${Math.max(0,Math.min(100,value))*3.6}deg`}}><div><b>{value}%</b><small>ready</small></div></div>}

function Dashboard({refresh,setRefresh,go}){
 const [data,setData]=useState(null),[error,setError]=useState(''); const load=useCallback(()=>api('/dashboard').then(setData).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load,refresh]);
 async function complete(id){await api(`/tasks/${id}/complete`,{method:'POST',body:JSON.stringify({confidence:3})});setRefresh(x=>x+1)}
 if(!data)return <div className="card pad">{error||'Loading…'}</div>;const pending=data.today_tasks.filter(t=>t.status!=='completed'),mins=pending.reduce((s,t)=>s+t.duration_minutes,0)
 return <><Header title="Your study command center" sub="Focus on the right topic at the right time, then measure what actually improved."/><section className="metrics"><div className="card readiness"><div><div className="eyebrow">EXAM READINESS</div><h3>{data.readiness.label}</h3><p>Mastery {data.readiness.mastery}% · Completion {data.readiness.completion}% · {data.readiness.quiz === null
  ? 'No quiz data yet'
  : `Quiz ${data.readiness.quiz}%`}</p><button className="secondary" onClick={()=>go('planner')}>Improve my plan →</button></div><Ring value={data.readiness.overall}/></div><Metric icon="◷" name="Focus remaining" value={`${Math.floor(mins/60)}h ${mins%60}m`} sub={`${pending.length} sessions today`}/><Metric icon="↗" name="Study streak" value={`${data.streak} days`} sub="Consistency compounds learning"/></section><section className="dashboard-grid"><div className="card pad"><Title kicker="TODAY" title="Teacher-planned focus" right={`${data.today_tasks.filter(t=>t.status==='completed').length}/${data.today_tasks.length} done`}/>{data.today_tasks.length===0?<Empty title="No study sessions remaining today" text="Your study plan is ready. Check the Planner for your next scheduled session." action="Open planner" onClick={()=>go('planner')}/>:<div className="task-list">{data.today_tasks.map(t=><Task key={t.id} t={t} onComplete={()=>complete(t.id)}/>)}</div>}</div><div className="card pad"><Title kicker="UPCOMING" title="Exam radar"/>{data.upcoming_exams.length===0?<Empty title="No upcoming exams" text="Add an exam date under Subjects."/>:data.upcoming_exams.map(e=><div className="exam" key={e.id}><i style={{background:e.color}}/><div><b>{e.name}</b><small>{niceDate(e.exam_date)} · {e.days_left} days left</small><div className="progress"><span style={{width:`${e.mastery}%`}}/></div></div><strong>{e.mastery}%</strong></div>)}</div></section></>
}
function Metric({icon,name,value,sub}){return <div className="card metric"><span className="metric-icon">{icon}</span><small>{name}</small><b>{value}</b><p>{sub}</p></div>}
function Title({kicker,title,right}){return <div className="title-row"><div><div className="eyebrow">{kicker}</div><h3>{title}</h3></div>{right&&<span className="badge">{right}</span>}</div>}
function Task({t,onComplete}){return <div className={`task ${t.status==='completed'?'done':''}`}><i style={{background:t.subject_color}}/><span className="task-time">{timeLabel(t.start_minute)}</span><div><b>{t.topic_name}</b><small>{t.subject_name} · {t.task_type} · {t.duration_minutes} min</small></div>{t.status==='completed'?<strong className="done-text">✓ Completed</strong>:<button className="mini" onClick={onComplete}>Mark done</button>}</div>}

function Subjects({refresh,setRefresh}){
 const [subjects,setSubjects]=useState([]),[error,setError]=useState(''),[topics,setTopics]=useState({}),[form,setForm]=useState({name:'',exam_date:todayPlus(30),importance:3,target_score:80,color:COLORS[0],notes:''});
 const load=useCallback(()=>api('/subjects').then(setSubjects).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load,refresh]);
 async function addSubject(e){e.preventDefault();try{await api('/subjects',{method:'POST',body:JSON.stringify(form)});setForm({...form,name:'',color:COLORS[subjects.length%COLORS.length]});setRefresh(x=>x+1)}catch(e){setError(e.message)}}
 async function addTopic(e,id){e.preventDefault();const d=topics[id]||{};if(!d.name)return;try{await api(`/subjects/${id}/topics`,{method:'POST',body:JSON.stringify({name:d.name,difficulty:Number(d.difficulty||3),mastery:Number(d.mastery||30),estimated_minutes:Number(d.estimated_minutes||120)})});setTopics({...topics,[id]:{}});setRefresh(x=>x+1)}catch(e){setError(e.message)}}
 async function del(id){if(confirm('Delete this subject and all topics?')){await api(`/subjects/${id}`,{method:'DELETE'});setRefresh(x=>x+1)}}
 async function seed(){try{await api('/demo/seed',{method:'POST'});setRefresh(x=>x+1)}catch(e){setError(e.message)}}
 return <><Header title="Subjects & syllabus" sub="Tell StudyPilot what you need to learn. Your syllabus remains authoritative."/>{error&&<div className="error page-error">{error}</div>}<div className="subjects-grid"><div className="card pad sticky"><Title kicker="ADD SUBJECT" title="New exam subject"/><form className="form compact" onSubmit={addSubject}><label>Subject name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Exam date<input required type="date" value={form.exam_date} onChange={e=>setForm({...form,exam_date:e.target.value})}/></label><div className="two"><label>Importance<select value={form.importance} onChange={e=>setForm({...form,importance:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Target %<input type="number" min="35" max="100" value={form.target_score} onChange={e=>setForm({...form,target_score:Number(e.target.value)})}/></label></div><label>Color<div className="colors">{COLORS.map(c=><button type="button" key={c} className={form.color===c?'selected':''} style={{background:c}} onClick={()=>setForm({...form,color:c})}/>)}</div></label><button className="primary">Add subject</button></form>{subjects.length===0&&<button className="secondary wide" onClick={seed}>Load demo subjects</button>}</div><div className="stack">{subjects.length===0?<div className="card pad"><Empty title="Your syllabus starts here" text="Add a subject manually or load demo data."/></div>:subjects.map(s=>{const d=topics[s.id]||{},m=s.topics.length?Math.round(s.topics.reduce((a,t)=>a+t.mastery,0)/s.topics.length):0;return <div className="card pad subject-card" key={s.id}><div className="subject-head"><i style={{background:s.color}}/><div><h3>{s.name}</h3><p>{niceDate(s.exam_date)} · Importance {s.importance}/5 · Target {s.target_score}%</p></div><button onClick={()=>del(s.id)}>×</button></div><div className="mastery"><span>Average mastery</span><b>{m}%</b><div className="progress"><span style={{width:`${m}%`}}/></div></div><div className="topics">{s.topics.map(t=><div key={t.id}><span><b>{t.name}</b><small>Difficulty {t.difficulty}/5 · {t.estimated_minutes} min</small></span><strong>{t.mastery}%</strong></div>)}</div><form className="topic-form" onSubmit={e=>addTopic(e,s.id)}><input required placeholder="Add topic/chapter" value={d.name||''} onChange={e=>setTopics({...topics,[s.id]:{...d,name:e.target.value}})}/><select value={d.difficulty||3} onChange={e=>setTopics({...topics,[s.id]:{...d,difficulty:e.target.value}})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>Difficulty {n}</option>)}</select><input type="number" min="20" value={d.estimated_minutes||120} onChange={e=>setTopics({...topics,[s.id]:{...d,estimated_minutes:e.target.value}})}/><button className="small-dark">+ Topic</button></form></div>})}</div></div></>
}

function Planner({refresh,setRefresh}){
 const [tasks,setTasks]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[days,setDays]=useState(21);const load=useCallback(()=>api(`/tasks?to_date=${todayPlus(45)}`).then(setTasks).catch(e=>setError(e.message)),[]);useEffect(()=>{load()},[load,refresh]);
 async function generate(){setBusy(true);setError('');try{await api('/planner/generate',{method:'POST',body:JSON.stringify({horizon_days:Number(days)})});setRefresh(x=>x+1)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function complete(t){const raw=prompt('Optional self-test score 0–100. Leave blank to skip.');const score=raw==null||raw===''?null:Number(raw);if(score!==null&&(Number.isNaN(score)||score<0||score>100))return;await api(`/tasks/${t.id}/complete`,{method:'POST',body:JSON.stringify({quiz_score:score,confidence:3})});setRefresh(x=>x+1)}
 const grouped=useMemo(()=>tasks.reduce((a,t)=>{(a[t.task_date]??=[]).push(t);return a},{}),[tasks]);return <><Header title="Smart study planner" sub="Balances urgency, weakness, difficulty, importance and your daily capacity."/><div className="card planner-bar"><div><div className="eyebrow">REGENERATE ANY TIME</div><h3>Build the next study cycle</h3><p>Completed sessions are preserved. Unfinished future sessions are replanned.</p></div><div><select value={days} onChange={e=>setDays(e.target.value)}>{[7,14,21,30,45].map(n=><option value={n} key={n}>{n} days</option>)}</select><button className="primary" disabled={busy} onClick={generate}>{busy?'Planning…':'✦ Generate smart plan'}</button></div></div>{error&&<div className="error page-error">{error}</div>}<div className="stack">{Object.keys(grouped).length===0?<div className="card pad"><Empty title="No study plan yet" text="Add subjects and topics first, then generate a plan."/></div>:Object.entries(grouped).map(([day,items])=><div className="card pad day" key={day}><div className="day-head"><span><b>{niceDate(day)}</b><small>{items.length} sessions</small></span><strong>{items.reduce((s,t)=>s+t.duration_minutes,0)} min</strong></div>{items.map(t=><Task key={t.id} t={t} onComplete={()=>complete(t)}/>)}</div>)}</div></>
}

function Coach({refresh}){
 const [subjects,setSubjects]=useState([]),[msg,setMsg]=useState('What should I focus on today to improve my exam readiness?'),[answer,setAnswer]=useState(''),[mode,setMode]=useState(''),[busy,setBusy]=useState(false),[topicId,setTopicId]=useState(''),[questions,setQuestions]=useState([]);useEffect(()=>{api('/subjects').then(s=>{setSubjects(s);const t=s.flatMap(x=>x.topics)[0];if(t)setTopicId(String(t.id))}).catch(()=>{})},[refresh]);const topicOptions=subjects.flatMap(s=>s.topics.map(t=>({...t,subject:s.name})));
 async function ask(e){e.preventDefault();setBusy(true);try{const d=await api('/ai/coach',{method:'POST',body:JSON.stringify({message:msg})});setAnswer(d.answer);setMode(d.mode)}catch(e){setAnswer(e.message)}finally{setBusy(false)}}async function quiz(){if(!topicId)return;const d=await api('/ai/quiz',{method:'POST',body:JSON.stringify({topic_id:Number(topicId),count:5,style:'mixed'})});setQuestions(d.questions)}
 return <><Header title="AI study coach" sub="Use AI for teaching support—not for silently changing your syllabus or timetable."/><div className="coach-grid"><div className="card pad coach"><span className="spark">✦</span><Title kicker="TEACHER MODE" title="Ask about your preparation"/><form onSubmit={ask}><textarea rows="6" value={msg} onChange={e=>setMsg(e.target.value)}/><button className="primary" disabled={busy}>{busy?'Thinking…':'Ask StudyPilot'}</button></form>{answer&&<div className="answer"><b>{mode==='gemini'?'Gemini-enhanced coach':'Built-in coach'}</b><div className="markdown-answer">
  <ReactMarkdown>{answer}</ReactMarkdown>
</div></div>}</div><div className="card pad"><Title kicker="ACTIVE RECALL" title="Quick quiz generator"/><p className="muted">Choose a topic and create recall/application questions.</p><select className="wide" value={topicId} onChange={e=>setTopicId(e.target.value)}><option value="">Choose a topic</option>{topicOptions.map(t=><option key={t.id} value={t.id}>{t.subject} — {t.name}</option>)}</select><button className="secondary wide" onClick={quiz} disabled={!topicId}>Generate 5 questions</button>{questions.length>0&&<ol className="quiz">{questions.map((q,i)=><li key={i}>{q}</li>)}</ol>}</div></div></>
}

function Resources(){const [q,setQ]=useState(''),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');async function search(e){e.preventDefault();if(q.trim().length<2)return;setBusy(true);setError('');try{setData(await api(`/resources/search?q=${encodeURIComponent(q.trim())}`))}catch(e){setError(e.message)}finally{setBusy(false)}}return <><Header title="Free learning resources" sub="Search public book and scholarly indexes without making paid content mandatory."/><form className="card resource-search" onSubmit={search}><div><div className="eyebrow">DISCOVER</div><h3>Find material for a topic</h3></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="e.g. support vector machines"/><button className="primary" disabled={busy}>{busy?'Searching…':'Search'}</button></form>{error&&<div className="error page-error">{error}</div>}{data?<div className="resource-grid"><Results title="BOOKS" items={data.books}/><Results title="RESEARCH" items={data.research}/></div>:<p className="center muted">Open Library is used for books; OpenAlex is used for scholarly discovery.</p>}</>}
function Results({title,items}){return <div className="card pad"><Title kicker={title} title={title==='BOOKS'?'Book discovery':'Academic resources'}/>{!items?.length?<p className="muted">No results returned.</p>:items.map((r,i)=><a className="resource" target="_blank" rel="noreferrer" href={r.url} key={i}><span><b>{r.title}</b><small>{r.subtitle||r.source}{r.year?` · ${r.year}`:''}</small></span><strong>{r.open_access===true?'Open ↗':'View ↗'}</strong></a>)}</div>}

function Settings({user,setUser}){const [form,setForm]=useState({name:user.name,daily_hours:user.daily_hours,preferred_start_hour:user.preferred_start_hour,session_minutes:user.session_minutes,break_minutes:user.break_minutes}),[msg,setMsg]=useState('');async function save(e){e.preventDefault();try{const d=await api('/users/me',{method:'PATCH',body:JSON.stringify({...form,daily_hours:Number(form.daily_hours),preferred_start_hour:Number(form.preferred_start_hour),session_minutes:Number(form.session_minutes),break_minutes:Number(form.break_minutes)})});setUser(d);setMsg('Saved. Regenerate your plan to apply the new capacity.')}catch(e){setMsg(e.message)}}return <><Header title="Study preferences" sub="Set realistic capacity. More hours does not automatically mean better learning."/><div className="card pad settings"><Title kicker="YOUR ROUTINE" title="Planner settings"/><form className="form" onSubmit={save}><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="two"><label>Study hours/day<input type="number" step="0.5" min="0.5" max="12" value={form.daily_hours} onChange={e=>setForm({...form,daily_hours:e.target.value})}/></label><label>Start hour (0–23)<input type="number" min="0" max="23" value={form.preferred_start_hour} onChange={e=>setForm({...form,preferred_start_hour:e.target.value})}/></label></div><div className="two"><label>Session minutes<input type="number" min="20" max="120" value={form.session_minutes} onChange={e=>setForm({...form,session_minutes:e.target.value})}/></label><label>Break minutes<input type="number" min="5" max="45" value={form.break_minutes} onChange={e=>setForm({...form,break_minutes:e.target.value})}/></label></div><button className="primary">Save settings</button>{msg&&<div className="notice">{msg}</div>}</form></div></>}

export default function App(){const [user,setUser]=useState(null),[loading,setLoading]=useState(Boolean(tokenStore.get())),[page,setPage]=useState('dashboard'),[refresh,setRefresh]=useState(0);const restore=useCallback(async()=>{if(!tokenStore.get()){setLoading(false);return}try{setUser(await api('/auth/me'))}catch{tokenStore.clear();setUser(null)}finally{setLoading(false)}},[]);useEffect(()=>{restore();const f=()=>{setUser(null);setLoading(false)};window.addEventListener('studypilot:logout',f);return()=>window.removeEventListener('studypilot:logout',f)},[restore]);if(loading)return <div className="splash"><span className="logo">S</span>Loading StudyPilot AI…</div>;if(!user)return <Auth onAuth={setUser}/>;const props={refresh,setRefresh};let content=page==='dashboard'?<Dashboard {...props} go={setPage}/>:page==='planner'?<Planner {...props}/>:page==='subjects'?<Subjects {...props}/>:page==='coach'?<Coach refresh={refresh}/>:page==='resources'?<Resources/>:<Settings user={user} setUser={setUser}/>;return <div className="shell"><Sidebar page={page} setPage={setPage} user={user} logout={()=>{tokenStore.clear();setUser(null)}}/><main>{content}</main></div>}
